### ISSUE TITLE
Looking up a specific quote is broken

### ISSUE THREAD

**Issue by dracco1993** [GreaterGamersLounge/bot_man#135]
See:
`https://discord.com/channels/168911139839672320/358061320786149386/803101733101764618`

**Comment by dracco1993** [comment]
```
2021-01-25T03:43:05.238551+00:00 app[bot.1]: D, [2021-01-25T03:43:05.142861 #4] DEBUG -- :   [1m[36mQuote Load (0.9ms)[0m  [1m[34mSELECT "quotes".* FROM "quotes" WHERE "quotes"."server_uid" = $1 AND "quotes"."id" = $2 LIMIT $3[0m  [["server_uid", 168911139839672320], ["id", 69], ["LIMIT", 1]]
2021-01-25T03:43:05.238553+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] Exception: #<NoMethodError: undefined method `nick' for nil:NilClass>
2021-01-25T03:43:05.238562+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/lib/bot/commands/quotes_container.rb:128:in `embed_for'
2021-01-25T03:43:05.238562+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/lib/bot/commands/quotes_container.rb:47:in `block in <class:QuotesContainer>'
2021-01-25T03:43:05.238563+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/lib/bot/container_wrapper.rb:12:in `block in proc_wrapper'
2021-01-25T03:43:05.238606+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/parser.rb:110:in `call'
2021-01-25T03:43:05.238630+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:226:in `execute_command'
2021-01-25T03:43:05.238667+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:323:in `simple_execute'
2021-01-25T03:43:05.238705+00:00 app[bot.1]: [ERROR : ct-64886 @ 2021-01-25 03:43:05.238] /app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:475:in `block in execute_chain'
```
