### ISSUE TITLE
Error when trying to list quotes

### ISSUE THREAD

**Issue by dracco1993** [GreaterGamersLounge/bot_man#35]
```
DEBUG -- SELECT "discord_users".* FROM "discord_users" WHERE "discord_users"."uid" = $1 ORDER BY "discord_users"."uid" ASC LIMIT $2 [0m  [["uid", 147930850091073536], ["LIMIT", 1]]
Exception: #<NoMethodError: undefined method `member' for nil:NilClass>
/app/lib/bot/commands/quotes_container.rb:38:in `block in <class:QuotesContainer>'
/app/lib/bot/container_wrapper.rb:12:in `block in proc_wrapper'
/app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/parser.rb:110:in `call'
/app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:226:in `execute_command'
/app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:323:in `simple_execute'
/app/vendor/bundle/ruby/2.7.0/gems/discordrb-3.3.0/lib/discordrb/commands/command_bot.rb:475:in `block in execute_chain'
```

**Comment by dracco1993** [comment]
Apparently this isn't an issue now?  🤔
I didn't do anything, soooo.... 🤷‍♂
